#!/bin/env -S=2 python -B

import os
import subprocess, re
from jinja2 import Template, Environment,FileSystemLoader
from os import path, walk, makedirs
from config import *
from sys import argv

from highlight import highlighter

def init_dirs():
    os.makedirs(md_dir       ,exist_ok=True)
    os.makedirs(tools_dir    ,exist_ok=True)
    os.makedirs(pages_dir    ,exist_ok=True)
    os.makedirs(static_dir   ,exist_ok=True)
    os.makedirs(template_dir ,exist_ok=True)


def read_file(file):
    with open(file, "r") as f:
        return f.read()



def md_to_html(content):
    """returns html content"""
    return subprocess.Popen(
        [path.join(tools_dir, "smu")],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE
    ).communicate(content.encode())[0].decode().rstrip("\n")

init_dirs()

env = Environment(loader=FileSystemLoader("templates"), autoescape=False)
for root, _, files in walk(md_dir):
    for file in files:
        md_path = path.join(root, file)
        print(md_path)
        md_content = read_file(md_path)

        md_to_html_content = md_to_html( md_content )

        content = []
        for linee in md_to_html_content.splitlines():

            line = linee
            if "<p>{% extends" in line:
                line = line.replace("<p>{% extends", "{% extends").replace('" %}', '" %}')
            if "<p>{% block" in line:
                line = line.replace("<p>{% block", "{% block").replace('" %}', '" %}')
            if "<p><div" in line:
                line = line.replace("<p><div", "<div").replace('</p>', '')
            if "<p></div" in line:
                line = line.replace("<p></div", "</div").replace('</p>', '')

            content.append(line)
        content = "\n".join(content)
        template = env.from_string(content)
        html = template.render(keywords=keywords)
        if len(argv) > 1 and argv[1] in ["--minify","-m"]:
            html = html.replace(" ", "").replace("\n\n","\n")
        if not (len(argv) > 1 and "-nh" in argv):
            html = highlighter(html)
        rel_path = path.relpath(md_path,md_dir).rstrip(".md") + ".html"
        makedirs(path.dirname(path.join(pages_dir,rel_path)), exist_ok=True)
        with open(path.join(pages_dir,rel_path), "w" ) as f:
            f.write(html)
