#!/bin/env -S=2 python -B

import os
import subprocess
from jinja2 import Environment,FileSystemLoader
from os import path, walk, makedirs
from config import *
from sys import argv


def init_dirs():
    os.makedirs(md_dir       ,exist_ok=True)
    os.makedirs(tools_dir    ,exist_ok=True)
    os.makedirs(pages_dir    ,exist_ok=True)
    os.makedirs(static_dir   ,exist_ok=True)
    os.makedirs(template_dir ,exist_ok=True)
    os.close(os.open(data_file, os.O_CREAT))


def read_file(file):
    with open(file, "r") as f:
        return f.read()



def md_to_html(content):
    """returns html content"""
    return subprocess.Popen(
        [path.join(tools_dir, "smu")],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE
    ).communicate(content.encode())[0].decode().rstrip("\n")

init_dirs()

env = Environment(loader=FileSystemLoader(template_dir), autoescape=False)
for root, _, files in walk(md_dir):
    for file in files:
        md_path = path.join(root, file)
        print(md_path)
        md_content = read_file(md_path)

        md_to_html_content = md_to_html( md_content )

        content = []
        for line in md_to_html_content.splitlines():
            for flter in filters:
                if flter[0] in line:
                    line = line.replace(flter[0],flter[1])
                    if flter[2]:
                        line = line.replace('</p>', '')


            content.append(line)
        content = "\n".join(content)
        template = env.from_string(content)
        html = template.render(keywords=keywords)
        if (len(argv) > 1 and "-nh" in argv) or highlighting:
            from highlight import highlighter
            html = highlighter(html)
        rel_path = path.relpath(md_path,md_dir).rstrip(".md") + ".html"
        makedirs(path.dirname(path.join(pages_dir,rel_path)), exist_ok=True)
        with open(path.join(pages_dir,rel_path), "w" ) as f:
            f.write(html)
